-- AgentRun 是模型调用的审计事实表：内部 id 仅用于关联，public_id 同时作为对外可查询的 Trace 标识。
-- workspace_id 不可为空且所有读取均与之组合，避免模型输入、输出、成本记录跨工作区泄露。
CREATE TABLE agent_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    agent_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    prompt_version VARCHAR(100) NOT NULL,
    model_name VARCHAR(120) NOT NULL,
    retrieval_version VARCHAR(100) NOT NULL,
    input_summary TEXT NOT NULL,
    output_text TEXT,
    evidence_json JSONB,
    prompt_tokens BIGINT,
    completion_tokens BIGINT,
    total_tokens BIGINT,
    latency_ms BIGINT,
    error_code VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ
);

-- 管理端按工作区读取最近 Trace，复合索引保证其他工作区记录不参与排序和扫描。
CREATE INDEX idx_agent_run_workspace_created
    ON agent_run(workspace_id, created_at DESC);
