-- P3 将 Organization 作为 Workspace 与企业知识文档的共同归属边界；它不是 P3 的登录或成员权限表。
-- 内部 bigint 主键继续服务于关系表和索引，public_id 预留给未来组织管理 API，不能泄露内部行号。
CREATE TABLE organization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- P3 尚无组织管理界面，单个默认组织保证已有和新建 Workspace 都有确定归属，避免产生无范围知识。
INSERT INTO organization (public_id, name, is_default)
VALUES ('00000000-0000-7000-8000-000000000001', '默认组织', TRUE);

-- 默认组织只能有一条；部分唯一索引允许未来 P4 新增普通组织而不引入无意义的布尔全表唯一约束。
CREATE UNIQUE INDEX uk_organization_default ON organization (is_default) WHERE is_default;

-- 先以可空列承接存量数据，随后通过默认组织回填，最后再收紧为不可空外键；该顺序避免生产迁移中断。
ALTER TABLE workspace ADD COLUMN organization_id BIGINT;

UPDATE workspace
SET organization_id = (SELECT id FROM organization WHERE is_default = TRUE)
WHERE organization_id IS NULL;

-- Workspace 是游戏/产品线分析上下文，不是聊天窗口；组织归属创建后不可被普通业务写操作改变。
ALTER TABLE workspace ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE workspace
    ADD CONSTRAINT fk_workspace_organization
    FOREIGN KEY (organization_id) REFERENCES organization(id);

-- 知识检索和未来组织管理会先按 organization_id 收敛 Workspace，索引避免回表扫描。
CREATE INDEX idx_workspace_organization_id ON workspace (organization_id);
