-- P3 的企业知识不再复用 knowledge_entry 占位表；文档、不可覆盖版本和检索切片分别建模以保留审计链。
-- 旧表不在本迁移删除，避免未确认的历史数据被破坏；新的知识 API 和 RAG 查询只使用以下三张表。

-- pgvector 是 P3 混合检索的数据库能力；部署 PostgreSQL 必须安装该扩展，不能退化为把向量当作普通文本。
CREATE EXTENSION IF NOT EXISTS vector;

-- 文档本体定义组织归属与可见范围；target_workspace_id 为空代表组织通用，非空代表仅当前游戏/产品线可见。
CREATE TABLE knowledge_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    organization_id BIGINT NOT NULL REFERENCES organization(id),
    target_workspace_id BIGINT REFERENCES workspace(id),
    document_type VARCHAR(32) NOT NULL,
    title VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_knowledge_document_type CHECK (
        document_type IN ('RELEASE_NOTE', 'KNOWN_ISSUE', 'SUPPORT_SOP', 'SENTIMENT_PLAYBOOK')
    )
);

-- 组织和目标 Workspace 是两层检索过滤条件，复合索引支持先收敛可见范围再关联已发布版本。
CREATE INDEX idx_knowledge_document_scope
    ON knowledge_document (organization_id, target_workspace_id, created_at DESC);

-- 每次上传创建独立版本，发布或失效只改变状态；禁止覆盖既有正文和版本号，保证历史引用仍可复核。
CREATE TABLE knowledge_document_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    document_id BIGINT NOT NULL REFERENCES knowledge_document(id),
    version_no INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    object_key VARCHAR(500) NOT NULL UNIQUE,
    checksum VARCHAR(64) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    content_length BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT uk_knowledge_document_version_no UNIQUE (document_id, version_no),
    CONSTRAINT ck_knowledge_document_version_status CHECK (
        status IN ('PENDING_REVIEW', 'PUBLISHED', 'EXPIRED', 'DELETED')
    ),
    CONSTRAINT ck_knowledge_document_version_size CHECK (content_length > 0)
);

-- 同一文档最多一个已发布版本，应用发布新版本前会使旧版本失效；部分唯一索引让审计状态继续保留。
CREATE UNIQUE INDEX uk_knowledge_document_published_version
    ON knowledge_document_version (document_id) WHERE status = 'PUBLISHED';
CREATE INDEX idx_knowledge_document_version_status
    ON knowledge_document_version (status, document_id, published_at DESC);

-- 只有发布成功后的正文会生成切片；向量列不可为空，杜绝半成品切片进入混合检索。
CREATE TABLE knowledge_chunk (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    version_id BIGINT NOT NULL REFERENCES knowledge_document_version(id),
    chunk_no INTEGER NOT NULL,
    content TEXT NOT NULL,
    content_tsv TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('simple'::regconfig, content)
    ) STORED,
    embedding vector(1024) NOT NULL,
    token_count INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_knowledge_chunk_no UNIQUE (version_id, chunk_no),
    CONSTRAINT ck_knowledge_chunk_no CHECK (chunk_no > 0),
    CONSTRAINT ck_knowledge_chunk_token_count CHECK (token_count > 0)
);

-- GIN 服务关键词召回，ivfflat 服务余弦语义召回；应用层以固定 RRF 合并两种排序而不是让模型写 SQL。
CREATE INDEX idx_knowledge_chunk_content_tsv
    ON knowledge_chunk USING GIN (content_tsv);
CREATE INDEX idx_knowledge_chunk_embedding
    ON knowledge_chunk USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);
CREATE INDEX idx_knowledge_chunk_version_id
    ON knowledge_chunk (version_id, chunk_no);
