-- P4 将登录账号、组织角色和 Workspace 可访问范围拆分存储：JWT 只标识账号，实际授权每次从这些关系表校验。
-- 该结构不能回填或覆盖既有 Organization/Workspace 归属；所有外部接口继续使用 public_id，内部 bigint 仅供关系和索引使用。
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    disabled_at TIMESTAMPTZ
);

-- 组织角色是权限语义的唯一来源；禁止把角色写入 JWT，以便成员角色变更立即生效。
CREATE TABLE organization_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organization(id),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_organization_member UNIQUE (organization_id, user_id),
    CONSTRAINT ck_organization_member_role CHECK (role IN ('OWNER', 'ANALYST', 'OPERATOR', 'VIEWER'))
);

-- 非 Owner 必须显式加入 Workspace；复合唯一约束防止重复授权和由此产生的多条权限判断结果。
CREATE TABLE workspace_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workspace_member UNIQUE (workspace_id, user_id)
);

-- 授权请求首先按用户和组织收敛，再按 Workspace 过滤；索引避免每个 API 请求扫描成员表。
CREATE INDEX idx_organization_member_user_organization ON organization_member (user_id, organization_id);
CREATE INDEX idx_workspace_member_user_workspace ON workspace_member (user_id, workspace_id);
