-- P4 审计日志只记录“谁在何工作区对什么目标做了何种动作”的不可变事实，禁止把原始命令体、密码、Token 或模型原文写入该表。
-- workspace_id 使用内部关系键以维持现有隔离查询性能；actor_user_public_id 与 target_public_id 使用外部 UUID，既可关联审计对象又不暴露自增主键。
CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    actor_user_public_id UUID NOT NULL,
    action VARCHAR(100) NOT NULL,
    target_public_id UUID NOT NULL,
    summary VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 调查中心和报告按工作区倒序读取审计事件，复合索引避免跨工作区扫描。
CREATE INDEX idx_audit_log_workspace_created_at ON audit_log (workspace_id, created_at DESC);

-- 目标对象的时间线需要按公开 UUID 定位，索引不包含动作内容或任何敏感摘要。
CREATE INDEX idx_audit_log_workspace_target ON audit_log (workspace_id, target_public_id);
