-- P4 将不可变 Alert 与可推进的调查流程分离：alert 始终只描述触发事实，investigation_case 承载排队、调查、人工复核等后续状态。
-- 同一 Workspace 下一个 Alert 只能对应一个调查卡片；该不可逆唯一约束是异步重试和事件重复投递的最终幂等保护。
CREATE TABLE investigation_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    alert_id BIGINT NOT NULL REFERENCES alert(id),
    async_task_id BIGINT UNIQUE REFERENCES async_task(id),
    status VARCHAR(30) NOT NULL,
    summary VARCHAR(1000),
    error_code VARCHAR(80),
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_investigation_case_workspace_alert UNIQUE (workspace_id, alert_id),
    CONSTRAINT ck_investigation_case_status CHECK (status IN ('queued', 'investigating', 'pending_review', 'confirmed', 'failed'))
);

-- 每条证据均为调查当时的快照，避免后续业务数据变化后覆盖曾用于人工判断的依据。
CREATE TABLE investigation_evidence_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    investigation_case_id BIGINT NOT NULL REFERENCES investigation_case(id),
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    source_type VARCHAR(50) NOT NULL,
    source_reference VARCHAR(200) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    sufficient BOOLEAN NOT NULL,
    source_url VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 调查中心的待办列表和报告证据均按工作区、状态、时间读取。
CREATE INDEX idx_investigation_case_workspace_status_created ON investigation_case (workspace_id, status, created_at DESC);

-- 证据读取始终按调查卡片和工作区双重过滤，阻断通过 case_id 跨工作区访问快照。
CREATE INDEX idx_investigation_evidence_case_workspace ON investigation_evidence_snapshot (investigation_case_id, workspace_id, created_at ASC);
