-- P4 处置流程以“提案”和“执行记录”分表：提案描述待人工审查的建议，执行记录描述真实的已确认动作；二者不能由 Agent 直接绕过创建状态变更。
-- 调查卡片补充 ignored/closed 两种人工终态，但 Alert 触发事实仍不被修改，保证告警与处置历史分离。
ALTER TABLE investigation_case DROP CONSTRAINT ck_investigation_case_status;
ALTER TABLE investigation_case ADD CONSTRAINT ck_investigation_case_status
    CHECK (status IN ('queued', 'investigating', 'pending_review', 'confirmed', 'ignored', 'closed', 'failed'));

CREATE TABLE action_proposal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    investigation_case_id BIGINT NOT NULL REFERENCES investigation_case(id),
    action VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    rationale VARCHAR(1000) NOT NULL,
    preview_json JSONB NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_action_proposal_case_action UNIQUE (investigation_case_id, action),
    CONSTRAINT ck_action_proposal_action CHECK (action IN ('CONFIRM', 'IGNORE', 'CLOSE')),
    CONSTRAINT ck_action_proposal_status CHECK (status IN ('pending', 'executed', 'withdrawn'))
);

CREATE TABLE action_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    investigation_case_id BIGINT NOT NULL REFERENCES investigation_case(id),
    action_proposal_id BIGINT NOT NULL REFERENCES action_proposal(id),
    actor_user_public_id UUID NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    action VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    summary VARCHAR(500) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_action_execution_workspace_key UNIQUE (workspace_id, idempotency_key),
    CONSTRAINT ck_action_execution_status CHECK (status IN ('executed', 'undone'))
);

-- 调查中心按卡片读取提案与执行记录，索引必须以 workspace_id 开头保证隔离查询路径。
CREATE INDEX idx_action_proposal_workspace_case ON action_proposal (workspace_id, investigation_case_id, created_at ASC);
CREATE INDEX idx_action_execution_workspace_case ON action_execution (workspace_id, investigation_case_id, created_at DESC);
