-- P4 人工纠错作为不可变候选记录保存，先完成双评测门禁再发布；不允许直接修改既有规则、别名或历史统计。
CREATE TABLE manual_correction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    investigation_case_id BIGINT REFERENCES investigation_case(id),
    kind VARCHAR(30) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_by_public_id UUID NOT NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_manual_correction_kind CHECK (kind IN ('ISSUE_ALIAS', 'RULE_CANDIDATE', 'EVALUATION_CASE')),
    CONSTRAINT ck_manual_correction_status CHECK (status IN ('pending_review', 'published', 'rejected'))
);

-- 纠错候选在调查中心按工作区和状态读取，不扫描其他组织的数据。
CREATE INDEX idx_manual_correction_workspace_status_created ON manual_correction (workspace_id, status, created_at DESC);
