-- Workspace 是所有业务数据的一级隔离边界；后续业务表必须通过 workspace_id 与其关联。
-- 内部 id 采用自增 bigint 以降低关联索引成本；对外 public_id 使用应用层生成的 UUIDv7。
CREATE TABLE workspace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 审计和管理页按创建时间倒序查看；不能使用允许出现空洞的自增 id 表示业务时间顺序。
CREATE INDEX idx_workspace_created_at ON workspace (created_at DESC);
