-- 长评论的多主题/混合情绪复核候选独立于历史指标：确认或忽略只改变候选状态，
-- 不回写 feedback_issue_link，避免人工动作悄然篡改已发布的趋势和告警事实。
CREATE TABLE feedback_review_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    feedback_event_id BIGINT NOT NULL REFERENCES feedback_event(id),
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    reason_code VARCHAR(40) NOT NULL,
    suggested_issue_key VARCHAR(100),
    suggested_sentiment VARCHAR(20),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMPTZ,
    CONSTRAINT uq_feedback_review_candidate_projection_event_reason
        UNIQUE (workspace_projection_id, feedback_event_id, reason_code),
    CONSTRAINT ck_feedback_review_candidate_status
        CHECK (status IN ('pending_review', 'confirmed', 'ignored'))
);

-- 复核页面永远先按 workspace 和状态读取，索引同时防止跨工作区扫描。
CREATE INDEX idx_feedback_review_candidate_workspace_status_created
    ON feedback_review_candidate (workspace_id, status, created_at DESC);
