-- L2 平台表达层快照：每条反馈在每次成功投影中恰好 1 行，与 0～2 行的 L1 feedback_issue_link
-- 是两张独立的分类事实表（原因见 spec "2026-07-28-l2-expression-l1-topic-layer-design.md" §2.1）。
-- 唯一约束 (workspace_projection_id, feedback_event_id) 与 feedback_issue_link 同口径防重试重复累计。
CREATE TABLE feedback_projection_annotation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    feedback_event_id BIGINT NOT NULL REFERENCES feedback_event(id),
    -- L2 五类固定枚举，全平台共用，不像 issue_id 那样需要 Workspace 私有目录表。
    primary_expression VARCHAR(30) NOT NULL
        CHECK (primary_expression IN ('expr_suggestion', 'expr_complaint', 'expr_praise', 'expr_neutral', 'expr_other')),
    expression_confidence DOUBLE PRECISION NOT NULL,
    -- v1 固定 'rule'；预留字段供未来 LLM 补位路径区分方法来源，不在本迁移引入新取值。
    expression_method VARCHAR(20) NOT NULL DEFAULT 'rule',
    -- 多意图同现且分差低于阈值时为 true；对应 L1 的 ambiguous，但 L2 不因此进复核。
    mixed_expression BOOLEAN NOT NULL DEFAULT FALSE,
    -- 冻结本次投影使用的 L2 规则版本，如 platform:expression:v1，便于追溯历史趋势口径。
    expression_rule_version VARCHAR(80) NOT NULL,
    -- 冻结本次投影绑定的 Workspace Topic Pack，用于 L1 钻取展示"当前使用哪个议题包"。
    topic_pack_id VARCHAR(80) NOT NULL,
    topic_pack_version VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_feedback_projection_annotation_projection_event
        UNIQUE (workspace_projection_id, feedback_event_id)
);

-- 按 Workspace + L2 类目 + 时间倒序是 Dashboard 首屏分布/趋势查询的主访问路径。
CREATE INDEX idx_feedback_projection_annotation_workspace_expression
    ON feedback_projection_annotation (workspace_id, primary_expression, created_at DESC);

-- L2 日粒度指标桶：与 issue_metric_bucket 同构，但按固定 primary_expression 枚举聚合，
-- 不需要类似 issue_catalog 的动态目录表——L2 是全平台共用的 5 类固定枚举。
CREATE TABLE expression_metric_bucket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    primary_expression VARCHAR(30) NOT NULL
        CHECK (primary_expression IN ('expr_suggestion', 'expr_complaint', 'expr_praise', 'expr_neutral', 'expr_other')),
    bucket_start TIMESTAMPTZ NOT NULL,
    feedback_count INTEGER NOT NULL,
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_expression_metric_bucket UNIQUE (workspace_id, primary_expression, bucket_start)
);

CREATE INDEX idx_expression_metric_bucket_workspace_time
    ON expression_metric_bucket (workspace_id, bucket_start DESC);
