-- 原始 CSV 仅保存到 MinIO；此表保存其受控对象键、映射状态和校验元数据，避免原文进入分析库。
CREATE TABLE feedback_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    source_type VARCHAR(40) NOT NULL,
    name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    config_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_feedback_source_workspace_name UNIQUE (workspace_id, name)
);

-- 文件对象键必须带有 Workspace 前缀；公开 UUID 供 API 使用，内部 source_id 只服务于去重和关联。
CREATE TABLE import_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    source_id BIGINT NOT NULL REFERENCES feedback_source(id),
    object_key VARCHAR(300) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes > 0),
    checksum_sha256 CHAR(64) NOT NULL,
    mapping_json JSONB,
    status VARCHAR(20) NOT NULL,
    retention_until TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_import_file_workspace_object UNIQUE (workspace_id, object_key)
);

-- 导入任务保留输入摘要和结果计数，允许页面轮询；真正的行级错误不保存未脱敏原文。
CREATE TABLE async_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    import_file_id BIGINT REFERENCES import_file(id),
    task_type VARCHAR(40) NOT NULL,
    status VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(200) NOT NULL,
    payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    result_json JSONB,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    error_code VARCHAR(80),
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_async_task_workspace_type_key UNIQUE (workspace_id, task_type, idempotency_key)
);

-- 分析表只接受 PII 脱敏后的文本；外部引用以不可逆哈希去重，不保存真实工单号或用户标识。
CREATE TABLE feedback_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    source_id BIGINT NOT NULL REFERENCES feedback_source(id),
    external_ref_hash CHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    source_kind VARCHAR(64) NOT NULL,
    sanitized_text TEXT NOT NULL,
    normalized_text TEXT NOT NULL,
    dimension_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    content_hash CHAR(64) NOT NULL,
    ingested_task_id BIGINT NOT NULL REFERENCES async_task(id),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_feedback_event_external_ref UNIQUE (workspace_id, source_id, external_ref_hash)
);

-- 这些索引对应导入结果、任务状态和后续按时间窗分析的最小访问路径。
CREATE INDEX idx_import_file_workspace_status ON import_file (workspace_id, status, created_at DESC);
CREATE INDEX idx_import_file_workspace_checksum ON import_file (workspace_id, checksum_sha256);
CREATE INDEX idx_async_task_workspace_created ON async_task (workspace_id, created_at DESC);
CREATE INDEX idx_async_task_workspace_file ON async_task (workspace_id, import_file_id, created_at DESC);
CREATE INDEX idx_feedback_event_workspace_occurred ON feedback_event (workspace_id, occurred_at DESC);
CREATE INDEX idx_feedback_event_workspace_content ON feedback_event (workspace_id, content_hash, occurred_at);
