-- 导入与投影故意使用两组状态：import_file.status 表示 CSV 是否已经被安全导入，
-- projection_status 表示这些脱敏事实是否已经进入看板。两者不能互相覆盖。
ALTER TABLE import_file
    ADD COLUMN projection_status VARCHAR(30) NOT NULL DEFAULT 'pending';

-- 自动投影保留规则版本和基线截点，确保看板数字、预警和后续排障均可追溯。
CREATE TABLE workspace_projection (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    async_task_id BIGINT NOT NULL UNIQUE REFERENCES async_task(id),
    status VARCHAR(30) NOT NULL,
    rule_version VARCHAR(80) NOT NULL,
    source_window_start TIMESTAMPTZ,
    source_window_end TIMESTAMPTZ,
    baseline_snapshot_at TIMESTAMPTZ,
    projected_at TIMESTAMPTZ,
    error_code VARCHAR(80),
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 一个投影可冻结多份来源文件；workspace_id 让关联读取始终具有显式租户边界。
CREATE TABLE projection_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    import_file_id BIGINT NOT NULL REFERENCES import_file(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_projection_file UNIQUE (workspace_projection_id, import_file_id)
);

-- 主题目录是 Workspace 私有的稳定名称空间；public_id 供未来看板路径使用，内部自增键用于关联。
CREATE TABLE issue_catalog (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    canonical_key VARCHAR(120) NOT NULL,
    canonical_name VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    first_seen_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_issue_catalog_workspace_key UNIQUE (workspace_id, canonical_key)
);

-- 别名记录规则或未来人工/模型建议的来源，但不允许它自行改写统计结果。
CREATE TABLE issue_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    issue_id BIGINT NOT NULL REFERENCES issue_catalog(id),
    normalized_alias VARCHAR(300) NOT NULL,
    origin VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_issue_alias_workspace_value UNIQUE (workspace_id, normalized_alias)
);

-- 反馈到主题的链接只引用已脱敏反馈，保存投影来源以便预警证据回溯。
CREATE TABLE feedback_issue_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    feedback_event_id BIGINT NOT NULL REFERENCES feedback_event(id),
    issue_id BIGINT NOT NULL REFERENCES issue_catalog(id),
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    assignment_method VARCHAR(30) NOT NULL,
    confidence NUMERIC(5, 4),
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_feedback_issue_link_projection_event_issue
        UNIQUE (workspace_projection_id, feedback_event_id, issue_id)
);

-- Data Cell 为规则和未来受限 LLM 分类提供固定粒度；本期 token 仅是字符估算，不调用模型。
CREATE TABLE data_cell (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    window_start TIMESTAMPTZ NOT NULL,
    window_end TIMESTAMPTZ NOT NULL,
    close_reason VARCHAR(30) NOT NULL,
    event_count INTEGER NOT NULL,
    estimated_tokens INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cell_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    data_cell_id BIGINT NOT NULL REFERENCES data_cell(id),
    issue_id BIGINT NOT NULL REFERENCES issue_catalog(id),
    mention_count INTEGER NOT NULL,
    sample_event_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_cell_issue UNIQUE (data_cell_id, issue_id)
);

-- 日粒度指标是看板趋势、报告和 EWMA 的共同事实来源，禁止由报告任务写入。
CREATE TABLE issue_metric_bucket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    issue_id BIGINT NOT NULL REFERENCES issue_catalog(id),
    bucket_start TIMESTAMPTZ NOT NULL,
    feedback_count INTEGER NOT NULL,
    dimension_summary_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_issue_metric_bucket UNIQUE (workspace_id, issue_id, bucket_start)
);

-- 每个主题一条可更新基线，最后处理桶防止晚到历史数据静默污染 EWMA。
CREATE TABLE issue_baseline_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    issue_id BIGINT NOT NULL REFERENCES issue_catalog(id),
    active_buckets INTEGER NOT NULL DEFAULT 0,
    baseline_ewma DOUBLE PRECISION NOT NULL DEFAULT 0,
    baseline_variance DOUBLE PRECISION NOT NULL DEFAULT 0,
    last_processed_bucket TIMESTAMPTZ,
    status VARCHAR(30) NOT NULL DEFAULT 'baseline_building',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_issue_baseline_profile UNIQUE (workspace_id, issue_id)
);

-- Alert 记录本次值、冻结基线和证据摘要，而不是只保存一个无法解释的布尔结果。
CREATE TABLE alert (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    issue_id BIGINT NOT NULL REFERENCES issue_catalog(id),
    workspace_projection_id BIGINT NOT NULL REFERENCES workspace_projection(id),
    bucket_start TIMESTAMPTZ NOT NULL,
    current_count INTEGER NOT NULL,
    baseline_ewma DOUBLE PRECISION NOT NULL,
    baseline_stddev DOUBLE PRECISION NOT NULL,
    z_score DOUBLE PRECISION NOT NULL,
    effective_threshold INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL,
    evidence_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 报告是对既有看板事实的只读快照，单独存储使“重新生成报告”不会驱动投影重算。
CREATE TABLE analysis_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    async_task_id BIGINT NOT NULL UNIQUE REFERENCES async_task(id),
    status VARCHAR(30) NOT NULL,
    report_version VARCHAR(80) NOT NULL,
    source_snapshot_at TIMESTAMPTZ NOT NULL,
    scope_json JSONB NOT NULL,
    report_json JSONB,
    error_code VARCHAR(80),
    error_message VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analysis_report_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_report_id BIGINT NOT NULL REFERENCES analysis_report(id),
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    import_file_id BIGINT NOT NULL REFERENCES import_file(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_analysis_report_file UNIQUE (analysis_report_id, import_file_id)
);

-- 索引对应自动投影调度、看板读取和按主题检查冷却期的最小访问路径。
CREATE INDEX idx_import_file_workspace_projection
    ON import_file (workspace_id, projection_status, created_at DESC);
CREATE INDEX idx_workspace_projection_workspace_status
    ON workspace_projection (workspace_id, status, created_at DESC);
CREATE INDEX idx_projection_file_workspace_file
    ON projection_file (workspace_id, import_file_id);
CREATE INDEX idx_feedback_issue_link_workspace_issue
    ON feedback_issue_link (workspace_id, issue_id, created_at DESC);
CREATE INDEX idx_issue_metric_bucket_workspace_issue_time
    ON issue_metric_bucket (workspace_id, issue_id, bucket_start DESC);
CREATE INDEX idx_alert_workspace_issue_time
    ON alert (workspace_id, issue_id, created_at DESC);
CREATE INDEX idx_analysis_report_workspace_created
    ON analysis_report (workspace_id, created_at DESC);
