-- 知识库条目表（RAG 知识库）
-- embedding 列为 TEXT 占位，后续切换为 pgvector vector(1536) 实现向量搜索。
CREATE TABLE IF NOT EXISTS knowledge_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(50) NOT NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'manual',
    embedding TEXT,
    metadata_json JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_knowledge_workspace_category ON knowledge_entry(workspace_id, category);