-- 对话记忆采用两个不可逆的关系表：会话负责恢复与归档，消息负责保存最终可见文本。
-- 内部 identity 主键仅服务于关联；public_id 对应 HTTP API，禁止把连续内部 id 暴露给客户端。
-- workspace_id 同时出现在两张表中是有意的隔离冗余，使 API 与领域服务可以在每次查询中强制限定工作区。
CREATE TABLE chat_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    title VARCHAR(100) NOT NULL,
    archived_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 刷新后恢复最近活动会话使用此索引；archived_at 参与过滤，避免归档会话拖慢活动列表查询。
CREATE INDEX idx_chat_session_workspace_active_updated
    ON chat_session(workspace_id, archived_at, updated_at DESC);

-- session_id 是内部关联键，workspace_id 是二次隔离键；role 约束与 ChatMessage 的最终消息模型一一对应。
CREATE TABLE chat_message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    workspace_id BIGINT NOT NULL REFERENCES workspace(id),
    session_id BIGINT NOT NULL REFERENCES chat_session(id),
    role VARCHAR(20) NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 历史渲染与最近 12 条短期记忆均按工作区、会话、时间读取，复合索引避免扫描其他会话的消息。
CREATE INDEX idx_chat_message_workspace_session_created
    ON chat_message(workspace_id, session_id, created_at DESC);
